# Generated by Django 5.0.6 on 2024-07-27 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_image_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post.images/', verbose_name='зображення')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'зображення поста',
                'verbose_name_plural': 'зображення постів',
            },
        ),
    ]
